// Purpose: Constants used in the project.

export const API_VERSION = "v1";
export const API_BASE_URL = `/api/${API_VERSION}`;
export const API_URLS = {
  AUTH: "auth",
  USER: "user",
  WEBHOOK: "webhook",
  MISC: "misc",
};

export const HttpResponseCode = {
  SUCCESS: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

// TODO: There might be  a better way to do this. Discuss this.

export enum RoosterErrorCode {
  // Use the following code when you want to send a generic error message. For eg db inseriton failed, etc.
  ROOSTER_OPERATION_FAILED = "ROOSTER_OPERATION_FAILED",

  ROOSTER_INVALID_INPUT = "ROOSTER_INVALID_INPUT",
  ROOSTER_USER_EXISTS = "ROOSTER_USER_EXISTS",
  ROOSTER_USER_NOT_FOUND = "ROOSTER_USER_NOT_FOUND",
  ROOSTER_API_KEY_INVALID = "ROOSTER_API_KEY_INVALID",
  ROOSTER_API_KEY_EXPIRED = "ROOSTER_API_KEY_EXPIRED",
  ROOSTER_API_KEY_BLOCKED = "ROOSTER_API_KEY_BLOCKED",
  ROOSTER_USER_BLOCKED = "ROOSTER_USER_BLOCKED",

  ROOSTER_WALLET_NOT_SET = "ROOSTER_WALLET_NOT_SET",
  ROOSTER_WALLET_NOT_FOUND = "ROOSTER_WALLET_NOT_FOUND",

  ROOSTER_TRANSACTION_FAILED = "ROOSTER_TRANSACTION_FAILED",
  ROOSTER_TRANSACTION_INVALID = "ROOSTER_TRANSACTION_INVALID",
  ROOSTER_TRANSACTION_EXPIRED = "ROOSTER_TRANSACTION_EXPIRED",
  ROOSTER_TRANSACTION_NOT_FOUND = "ROOSTER_TRANSACTION_NOT_FOUND",
  ROOSTER_TRANSACTION_ALREADY_PROCESSED = "ROOSTER_TRANSACTION_ALREADY_PROCESSED",
}

export enum RoosterStatusCode {
  // Use the following code when you want to send a generic success message. For eg db inseriton, rsa keys genenrated etc.
  ROOSTER_OPERATION_SUCCESSFUL = "ROOSTER_OPERATION_SUCCESSFUL",

  ROOSTER_USER_CREATED = "ROOSTER_USER_CREATED",
  ROOSTER_USER_UPDATED = "ROOSTER_USER_UPDATED",
  ROOSTER_USER_DELETED = "ROOSTER_USER_DELETED",
  ROOSTER_USER_BLOCKED = "ROOSTER_USER_BLOCKED",
  ROOSTER_USER_ACTIVE = "ROOSTER_USER_ACTIVE",
  ROOSTER_USER_INACTIVE = "ROOSTER_USER_INACTIVE",
  ROOSTER_USER_WALLET_CREATED = "ROOSTER_USER_WALLET_CREATED",
  ROOSTER_USER_DISABLED = "ROOSTER_USER_DISABLED",
  ROOSTER_USER_PENDING_ACTIONS = "ROOSTER_USER_PENDING_ACTIONS",
  ROOSTER_USER_VERIFIED = "ROOSTER_USER_VERIFIED",
  ROOSTER_USER_FOUND = "ROOSTER_USER_FOUND",
  ROOSTER_USER_EXISTS = "ROOSTER_USER_EXISTS",
  ROOSTER_USER_NOT_FOUND = "ROOSTER_USER_NOT_FOUND",

  ROOSTER_WALLET_SET = "ROOSTER_WALLET_SET",
  ROOSTER_WALLET_FOUND = "ROOSTER_WALLET_FOUND",

  ROOSTER_TRANSACTION_INITIATED = "ROOSTER_TRANSACTION_INITIATED",
  ROOSTER_TRANSACTION_PROCESSING = "ROOSTER_TRANSACTION_PROCESSING",
  ROOSTER_TRANSACTION_SENT_TO_CHAIN = "ROOSTER_TRANSACTION_SENT_TO_CHAIN",
  ROOSTER_TRANSACTION_SUCCESSFUL = "ROOSTER_TRANSACTION_SUCCESSFUL",
  ROOSTER_TRANSACTION_CANCELLED = "ROOSTER_TRANSACTION_CANCELLED",
  ROOSTER_TRANSACTION_EXPIRED = "ROOSTER_TRANSACTION_EXPIRED",
}

// export {
//   API_URLS,
//   API_BASE_URL,
//   HttpResponseCode,
//   RoosterErrorCode,
//   RoosterStatusCode,
// };
